# Generated by Django 5.2.7 on 2025-10-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('public', 'Public'), ('artist', 'Artist')], default='public', max_length=20),
        ),
    ]
